INSERT INTO CLIENT (LAST_NAMES, DNI, NAME, PHONE, COUNTRY) VALUES ('PEREZ', '1', 'ROBERTO', '093939393', 'CR');
INSERT INTO CLIENT (LAST_NAMES, DNI, NAME, PHONE, COUNTRY) VALUES ('SANCHEZ', '2', 'RAUL', '093223333', 'GUA');
INSERT INTO CLIENT (LAST_NAMES, DNI, NAME, PHONE, COUNTRY) VALUES ('SANCHEZ PAZMINO', '11', 'PATRICIO', '092222', 'CR');
INSERT INTO CLIENT (LAST_NAMES, DNI, NAME, PHONE, COUNTRY) VALUES ('SANCHEZ SALAZAR', '111', 'MAURICIO', '0933333', 'EC');
INSERT INTO CLIENT (LAST_NAMES, DNI, NAME, PHONE, COUNTRY) VALUES ('SANCHEZ SALAZAR', '1111', 'HORACIO', '0934555', 'EC');

INSERT INTO ADDRESS (ADDRESS, CODE, CLIENT_ID) VALUES ('10 de agosto', 'n31', 1);
INSERT INTO ADDRESS (ADDRESS, CODE, CLIENT_ID) VALUES ('Av. Amazonas', 'n100', 1);
INSERT INTO ADDRESS (ADDRESS, CODE, CLIENT_ID) VALUES ('Av. Prensa', 'n1', 2);

INSERT INTO ACCOUNT (ACCOUNT_NUMBER, TYPE, CLIENT_ID, STATE) VALUES ('22222', 'AHORRO', 1, true);
INSERT INTO ACCOUNT (ACCOUNT_NUMBER, TYPE, CLIENT_ID, STATE) VALUES ('33333', 'CORRIENTE', 1, false);

INSERT INTO CARD (CARD_NUMBER, TYPE, STATE, CLIENT_ID) VALUES('12345', 'DEBIT', true, 1);
INSERT INTO CARD (CARD_NUMBER, TYPE, STATE, CLIENT_ID) VALUES('56789', 'CREDIT', true, 2);
INSERT INTO CARD (CARD_NUMBER, TYPE, STATE, CLIENT_ID) VALUES('09876', 'DEBIT', false, 2);

INSERT INTO INVESTMENT (NUMBER, TYPE, STATE, CLIENT_ID) VALUES('12345', 'SAVING', true, 1);
INSERT INTO INVESTMENT (NUMBER, TYPE, STATE, CLIENT_ID) VALUES('56789', 'CREDIT', true, 2);
INSERT INTO INVESTMENT (NUMBER, TYPE, STATE, CLIENT_ID) VALUES('09876', 'DEBIT', false, 2);
